// <auto-generated />
using System;
using ASPBoilerplate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPBoilerplate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241224233743_Intial")]
    partial class Intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ASPBoilerplate.Modules.File.FileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Storage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CreatedAt = new DateTime(2024, 12, 24, 18, 37, 42, 786, DateTimeKind.Local).AddTicks(2470),
                            IsUsed = true,
                            Location = "file1.txt",
                            Name = "File 1",
                            Storage = 0,
                            UpdatedAt = new DateTime(2024, 12, 24, 18, 37, 42, 794, DateTimeKind.Local).AddTicks(4580)
                        },
                        new
                        {
                            Id = "2",
                            CreatedAt = new DateTime(2024, 12, 24, 18, 37, 42, 794, DateTimeKind.Local).AddTicks(4720),
                            IsUsed = true,
                            Location = "file2.txt",
                            Name = "File 2",
                            Storage = 0,
                            UpdatedAt = new DateTime(2024, 12, 24, 18, 37, 42, 794, DateTimeKind.Local).AddTicks(4720)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
